### ISSUE TITLE
Request push access

### ISSUE THREAD

**Issue by lazersos** [joseluisvelasco/KNOSOS#2]
Hello, I've made modification to the makefile for Macports and the MPCDF clusters.  I'd like to push my branch to the repo.

**Comment by joseluisvelasco** [comment]
Hi, 
there are small differences between the code here and the code at https://github.com/joseluisvelasco/STELLOPT/tree/CIEMAT . The main one is that there is no knosos_stellopt.f90 here (the file that replaces the "main" file, knosos.f90). Do you want to work with this code or the other one? I can take care of eliminating these differences later.

**Comment by lazersos** [comment]
It's in the repo I have.

**Comment by joseluisvelasco** [comment]
Oh, yes, right. There are differences, but this is not one of them.
